---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deployer-watsonxdata-git-repo-access
  namespace: openshift-gitops
spec: 
  data:
  - secretKey: git_token
    remoteRef: 
      key: dcd30d85-16a3-8cf0-bb5e-836fc2ac9b52
  refreshInterval: 1h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: deployer-watsonxdata-git-repo-access
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      engineVersion: v2
      type: Opaque
      data:
        type: git
        url: 'https://github.com/cloud-native-toolkit/deployer-watsonxdata.git'
        username: not-used
        project: default
        password: '{{ .git_token }}'
