---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: deploy-watsonxdata-
  namespace: default
spec:
  pipelineRef:
    name: deploy-watsonxdata
  taskRunTemplate:
    serviceAccountName: pipeline
    podTemplate:
      securityContext:
        fsGroup: 65532
  timeouts:
    pipeline: "6h0m0s"
  workspaces:
    - name: manifest-dir
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: ocs-storagecluster-cephfs
          volumeMode: Filesystem
        status: {}
